// Generated by https://quicktype.io

export interface CastDetailsModel {
    id:          number;
    name:        string;
    gender:      string;
    tmdbUrl:     string;
    profilePath: string;
    roles:       MovieCastModel[];
}

export interface MovieCastModel {
    movieId:   number;
    character: string;
    posterUrl: string;
}
