// Generated by https://quicktype.io

import { MovieCardModel } from "./MovieCardModel";

export interface GenrePageModel {
    name:            string;
    pageIndex:       number;
    pageSize:        number;
    totalPages:      number;
    totalRowCount:   number;
    hasPreviousPage: boolean;
    hasNextPage:     boolean;
    data:            MovieCardModel[];
}

