// Generated by https://quicktype.io

export interface PurchaseRequestModel {
    purchaseNumber:   string;
    totalPrice:       number;
    purchaseDateTime: string;
    movieId:          number;
    posterUrl:        string;
}
