// Generated by https://quicktype.io

export interface UserRegisterModel {
    firstName:   string;
    lastName:    string;
    email:       string;
    password:    string;
    dateOfBirth: string;
}
